name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-from-miniconda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
      - name: run tests directly
        run: |
          conda activate test
          conda install geometric -c conda-forge
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/share/miniconda/envs/test/lib
          echo `which python`
          cargo test --examples
