name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-from-miniconda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          python-version: "3.10"
      - name: run tests directly
        run: |
          conda install geometric -c conda-forge
          export LD_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib:$LD_LIBRARY_PATH
          export PATH=/usr/share/miniconda/envs/test/bin:$PATH
          echo `which python`
          cargo test --examples
