name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-from-miniconda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          python-version: "3.10"
      - name: test
        run: |
          conda install geometric -c conda-forge
          export LD_LIBRARY_PATH=/usr/share/miniconda/lib:$LD_LIBRARY_PATH
          export PATH=/usr/share/miniconda/bin:$PATH
          python -c "import sys; print(sys.version)"
          python -c "import numpy; print(numpy.__version__)"
          python -c "import geometric; print(geometric.__version__)"
          cargo test --examples
